gcc -fPIC -m64 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement    -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .xencov.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE   -Werror -include /root/xen-4.13.0/tools/misc/../../tools/config.h -I/root/xen-4.13.0/tools/misc/../../tools/libs/evtchn/include -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/libxc/include -I/root/xen-4.13.0/tools/misc/../../tools/libs/toollog/include -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/libs/foreignmemory/include -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/libs/devicemodel/include -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/include -D__XEN_TOOLS__ -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/xenstore/include -I/root/xen-4.13.0/tools/misc/../../tools/include  -c -o cov.o cov.c

gcc -fPIC -m64 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement    -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .xencov.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE   -Werror -include /root/xen-4.13.0/tools/misc/../../tools/config.h -I/root/xen-4.13.0/tools/misc/../../tools/libs/evtchn/include -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/libxc/include -I/root/xen-4.13.0/tools/misc/../../tools/libs/toollog/include -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/libs/foreignmemory/include -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/libs/devicemodel/include -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/include -D__XEN_TOOLS__ -I/root/xen-4.13.0/tools/misc/../../tools/include -I/root/xen-4.13.0/tools/misc/../../tools/xenstore/include -I/root/xen-4.13.0/tools/misc/../../tools/include  -c -o reset.o reset.c



gcc   -o cov cov.o  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toollog  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/evtchn  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toollog  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/gnttab  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/call  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/foreignmemory  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toollog  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/devicemodel /root/xen-4.13.0/tools/misc/../../tools/libxc/libxenctrl.so

gcc   -o reset reset.o  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toollog  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/evtchn  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toollog  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/gnttab  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/call  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/foreignmemory  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toollog  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/toolcore  -Wl,-rpath-link=/root/xen-4.13.0/tools/misc/../../tools/libs/devicemodel /root/xen-4.13.0/tools/misc/../../tools/libxc/libxenctrl.so


